#!/usr/bin/env ruby
# test/cairo_glyph_source_test.rb
#
# Round 23 (F-1) locks for the Glyphs-mode glyph SOURCE layer
# (cairo_glyph_source.rb):
#
#   1. Fixture parse -> model-space loops -> extents. The committed fixture
#      test/fixtures/cairo_glyph_source/condensed_span.svg is SYNTHETIC:
#      generated by the bundled pdftocairo (-svg -f 1 -l 1) from a
#      hand-written 696-byte PDF (base-14 Helvetica, one condensed span
#      "CONDENSED TITLE BLOCK PARITY CHECK" with Tm = [8 0 0 10 72 300],
#      i.e. 10 pt tall at 0.8 horizontal scale, plus a 12 pt "NORMAL SPAN"
#      control at (72,200) on a 612x396 page). The source PDF itself stays
#      out of version control (repo-wide *.pdf ignore = PRIV-1 backstop);
#      the content stream to regenerate it verbatim:
#        BT /F1 1 Tf 8 0 0 10 72 300 Tm (CONDENSED TITLE BLOCK PARITY CHECK) Tj ET
#        BT /F1 12 Tf 1 0 0 1 72 200 Tm (NORMAL SPAN) Tj ET
#      No owner document is involved anywhere in this test (PRIV-1).
#   2. Coordinate mapping against hand-computed values (viewBox offsets,
#      import scale, y_offset, matrix placements).
#   3. VALUE lock: the condensed span's cairo outline ink extent lands
#      within 2% (+1 pt side-bearing floor) of the PDF-DECLARED extent
#      (pdftotext -bbox-layout words, constants below).
#   4. Per-import source decision: cairo preferred; missing binary =>
#      internal source, visible fallback_reason, no silent demotion after
#      a delivered SVG page (single decision per import).
#   5. False-green guard: zero glyph ink + extractor spans = source failure.
#   6. Span matching (R17-3): runs matched/unmatched + provenance span_ids.
#   7. Report telemetry: extra.glyph_source carries source/reason/counts.
#
# Ruby 2.2 compatible syntax throughout (RB22).

require_relative 'mesh_text_scaling_test'
require_relative '../extracted/sketchup_ext/bc_pdf_vector_importer/cairo_glyph_source'
require_relative '../extracted/sketchup_ext/bc_pdf_vector_importer/qa_report'

# The shared stubs' Point3d is minimal; SvgTextRenderer's path tokenizer
# needs #distance for curve flattening and duplicate-point cleanup.
module Geom
  class Point3d
    unless method_defined?(:distance)
      def distance(other)
        dx = x.to_f - other.x.to_f
        dy = y.to_f - other.y.to_f
        dz = z.to_f - other.z.to_f
        Math.sqrt((dx * dx) + (dy * dy) + (dz * dz))
      end
    end
  end
end

class CairoGlyphSourceTest < Minitest::Test
  CGS = BlueCollarSystems::PDFVectorImporter::CairoGlyphSource
  SVG_R = BlueCollarSystems::PDFVectorImporter::SvgTextRenderer
  QAR = BlueCollarSystems::PDFVectorImporter::QAReport

  FIXTURE_DIR = File.join(File.dirname(__FILE__), 'fixtures', 'cairo_glyph_source')
  FIXTURE_SVG = File.join(FIXTURE_DIR, 'condensed_span.svg')
  FIXTURE_PDF = File.join(FIXTURE_DIR, 'condensed_span.pdf')

  # Page box of the synthetic fixture (letter-half landscape).
  FIXTURE_MEDIA_BOX = [0, 0, 612, 396].freeze

  # PDF-DECLARED extents from `pdftotext -bbox-layout condensed_span.pdf`
  # (x in PDF points; the condensed line is the five words below):
  #   CONDENSED 72.000 .. 123.112 | TITLE .. | BLOCK .. | PARITY ..
  #   CHECK 209.808 .. 237.808
  DECLARED_X0_PT = 72.0
  DECLARED_X1_PT = 237.808
  # Condensed-span baseline: Tm f = 300 (y-up); SVG pen y (top-down) = 96.
  CONDENSED_BASELINE_Y_PDF = 300.0

  def fixture_svg
    File.open(FIXTURE_SVG, 'rb') { |f| f.read }
  end

  # ── 1+2. parse -> loops -> extents, known-value coordinate mapping ──────

  def test_fixture_parses_to_placed_outline_loops
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    refute_empty placed, 'fixture must produce placed glyph outlines'
    # Every placed glyph carries loops of >= 2 points and a pen position.
    placed.each do |entry|
      refute_empty entry[:loops]
      entry[:loops].each { |pts| assert_operator pts.length, :>=, 2 }
      assert_kind_of Array, entry[:pen_pdf]
    end
    # 34 condensed chars (5 spaces -> empty defs skipped) + NORMAL SPAN.
    assert_operator placed.length, :>=, 35
  end

  def test_condensed_span_pen_positions_match_declared_baseline
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    pens = placed.map { |entry| entry[:pen_pdf] }
    condensed = pens.select { |pen| (pen[1] - CONDENSED_BASELINE_Y_PDF).abs < 0.5 }
    refute_empty condensed, 'condensed baseline pens must be found at y=300 (y-up)'
    first_pen_x = condensed.map { |pen| pen[0] }.min
    # Probe lock: first-glyph pen within 0.5 pt of the declared span xMin.
    assert_in_delta DECLARED_X0_PT, first_pen_x, 0.5
  end

  # ── 3. VALUE lock: cairo ink extent vs PDF-declared extent ──────────────

  def test_condensed_span_ink_extent_within_declared_tolerance
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    # Select the condensed line by pen baseline (y-up 300 => model inches
    # y ~ 300/72). Model space: media origin at 0, scale 1.0.
    line = placed.select do |entry|
      (entry[:pen_pdf][1] - CONDENSED_BASELINE_Y_PDF).abs < 0.5
    end
    extent = CGS.loops_extent(line)
    refute_nil extent

    ink_w_pt = (extent[2] - extent[0]) * 72.0
    declared_w_pt = DECLARED_X1_PT - DECLARED_X0_PT
    # Side-bearing-aware tolerance (probe): 2% of the declared width plus
    # a 1 pt absolute floor.
    tolerance = [declared_w_pt * 0.02, 1.0].max
    assert_in_delta declared_w_pt, ink_w_pt, tolerance,
                    'condensed cairo outline ink must land within 2% (+1pt ' \
                    'floor) of the PDF-declared span extent'
    # And the ink must sit AT the declared position, not merely match width.
    assert_in_delta DECLARED_X0_PT, extent[0] * 72.0, 1.0
    assert_in_delta DECLARED_X1_PT, extent[2] * 72.0, 1.0
  end

  def test_import_scale_and_y_offset_apply_to_loops
    placed_1x = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    placed_2x = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX,
                                      scale: 2.0, y_offset: 5.0)
    e1 = CGS.loops_extent(placed_1x)
    e2 = CGS.loops_extent(placed_2x)
    assert_in_delta e1[0] * 2.0, e2[0], 1.0e-6, 'x scales with import scale'
    assert_in_delta (e1[2] - e1[0]) * 2.0, e2[2] - e2[0], 1.0e-6
    assert_in_delta (e1[1] * 2.0) + 5.0, e2[1], 1.0e-6, 'y adds the page y_offset'
  end

  def test_known_value_coordinate_mapping_simple_use
    # Hand-checkable synthetic SVG: one square glyph (baseline-relative,
    # y negative-up), one placement at pen (72, 96) on a 612x396 page.
    # Model inches: pen x = 1.0, pen y = (396-96)/72 = 4.1666..; the glyph
    # box [0..7.2]x[-7.2..0] maps to x 1.0..1.1, y 4.1666..4.2666.
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="612pt" height="396pt" ' \
          'viewBox="0 0 612 396"><defs><g><g id="glyph-0-0">' \
          '<path d="M 0 0 L 7.2 0 L 7.2 -7.2 L 0 -7.2 Z M 0 0 "/>' \
          '</g></g></defs><g>' \
          '<use xlink:href="#glyph-0-0" x="72" y="96"/></g></svg>'
    placed = CGS.model_space_loops(svg, FIXTURE_MEDIA_BOX)
    assert_equal 1, placed.length
    assert_in_delta 72.0, placed[0][:pen_pdf][0], 1.0e-6
    assert_in_delta 300.0, placed[0][:pen_pdf][1], 1.0e-6
    extent = CGS.loops_extent(placed)
    assert_in_delta 1.0, extent[0], 1.0e-6
    assert_in_delta 1.1, extent[2], 1.0e-6
    assert_in_delta 300.0 / 72.0, extent[1], 1.0e-6
    assert_in_delta 307.2 / 72.0, extent[3], 1.0e-6
  end

  def test_known_value_coordinate_mapping_matrix_use
    # Rotated/sheared placements arrive as matrix() on the <use>; the pen is
    # the matrix translation (plus additive x/y). 90-degree rotation matrix
    # [0 1 -1 0]: local (x,-y) with y-flip maps x'=a*x-c*y, y'=-b*x+d*y.
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="612pt" height="396pt" ' \
          'viewBox="0 0 612 396"><defs><g><g id="glyph-0-0">' \
          '<path d="M 0 0 L 7.2 0 "/>' \
          '</g></g></defs><g>' \
          '<use xlink:href="#glyph-0-0" x="10" y="20" ' \
          'transform="matrix(0,1,-1,0,62,76)"/></g></svg>'
    placed = CGS.model_space_loops(svg, FIXTURE_MEDIA_BOX)
    assert_equal 1, placed.length
    assert_in_delta 72.0, placed[0][:pen_pdf][0], 1.0e-6
    assert_in_delta 300.0, placed[0][:pen_pdf][1], 1.0e-6
    pts = placed[0][:loops][0]
    # Local run along +x, rotated 90 deg: model dx = 0, dy = -b*x = -0.1 in.
    assert_in_delta 0.0, pts[1].x - pts[0].x, 1.0e-6
    assert_in_delta(-0.1, pts[1].y - pts[0].y, 1.0e-6)
  end

  # ── 4. per-import source decision + fallback on missing binary ──────────

  def with_renderer_stub(value)
    original = SVG_R.method(:find_svg_renderer)
    SVG_R.define_singleton_method(:find_svg_renderer) { value }
    yield
  ensure
    SVG_R.define_singleton_method(:find_svg_renderer, original)
  end

  def test_decision_prefers_cairo_when_pdftocairo_present
    with_renderer_stub(kind: :pdftocairo, exe: 'x') do
      stats = {}
      decision = CGS.import_decision(stats)
      assert_equal 'cairo_svg', decision[:source]
      assert_nil decision[:fallback_reason]
      assert_same decision, stats[:glyph_source], 'decision must be recorded'
      assert_same decision, CGS.import_decision(stats), 'single per-import decision'
    end
  end

  def test_decision_falls_back_internal_when_no_svg_renderer
    with_renderer_stub(nil) do
      stats = {}
      decision = CGS.import_decision(stats)
      assert_equal 'internal', decision[:source]
      assert_equal 'pdftocairo_missing', decision[:fallback_reason]
      assert CGS.internal_source?(decision)
      refute CGS.svg_source?(decision)
    end
  end

  def test_decision_names_mutool_honestly
    with_renderer_stub(kind: :mutool, exe: 'x') do
      decision = CGS.import_decision({})
      assert_equal 'mupdf_svg', decision[:source]
      assert_equal 'pdftocairo_missing', decision[:fallback_reason]
      assert CGS.svg_source?(decision)
    end
  end

  def test_demotion_is_visible_and_refused_after_a_delivered_page
    with_renderer_stub(kind: :pdftocairo, exe: 'x') do
      decision = CGS.import_decision({})
      assert CGS.demote_to_internal!(decision, 'pdftocairo_timeout')
      assert_equal 'internal', decision[:source]
      assert_equal 'pdftocairo_timeout', decision[:fallback_reason]

      # A decision that already delivered an SVG page must NOT demote
      # (single per-import decision — never mix sources mid-import).
      delivered = CGS.import_decision({})
      delivered[:pages] = 1
      refute CGS.demote_to_internal!(delivered, 'pdftocairo_failed')
      assert_equal 'cairo_svg', delivered[:source]
    end
  end

  def test_failure_reasons_map_to_recorded_vocabulary
    assert_equal 'pdftocairo_missing', CGS.failure_reason(reason: 'no_renderer')
    assert_equal 'pdftocairo_timeout', CGS.failure_reason(reason: 'timeout')
    assert_equal 'pdftocairo_failed', CGS.failure_reason(reason: 'render_failed')
    assert_equal 'pdftocairo_failed', CGS.failure_reason({})
    assert_equal 'svg_zero_placements', CGS.failure_reason(reason: 'svg_zero_placements')
  end

  # ── 5. false-green guard ─────────────────────────────────────────────────

  SpanItem = Struct.new(:text, :font_name, :source_span_id,
                        :bbox_x0, :bbox_y0, :bbox_x1, :bbox_y1)

  def test_zero_glyph_ink_with_extractor_spans_is_a_source_failure
    spans = [SpanItem.new('CUSTOMER', 'pdftotext', 'text_span:1:0',
                          100.0, 100.0, 150.0, 110.0)]
    assert CGS.zero_placement_false_green?({ glyphs: 0 }, spans)
    refute CGS.zero_placement_false_green?({ glyphs: 12 }, spans)
    refute CGS.zero_placement_false_green?({ glyphs: 0 }, []),
           'a genuinely empty page is not a false green'
    refute CGS.zero_placement_false_green?({ glyphs: 0 }, [SpanItem.new('  ')])
  end

  # ── 6. span matching + provenance (R17-3) ────────────────────────────────

  def test_match_spans_counts_and_provenance_span_ids
    spans = [
      SpanItem.new('CUSTOMER', 'pdftotext', 'text_span:1:0',
                   100.0, 100.0, 150.0, 110.0),
      SpanItem.new('ORPHAN', 'pdftotext', 'text_span:1:1',
                   400.0, 200.0, 440.0, 210.0)
    ]
    pens = [
      { x: 101.0, y: 101.5 },  # inside CUSTOMER
      { x: 120.0, y: 102.0 },  # inside CUSTOMER
      { x: 300.0, y: 300.0 }   # matches nothing
    ]
    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)
    assert_equal 1, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    assert_equal 1, match[:placements_unmatched]
    assert_equal ['CUSTOMER'], match[:matched_items].map { |i| i.text }

    bucket = []
    CGS.record_span_provenance(bucket, 1, match[:matched_items], 'cairo_svg')
    assert_equal 1, bucket.length
    entry = bucket[0]
    assert_equal 'text_span:1:0', entry[:span_id]
    assert_equal 'glyph_outline', entry[:created_entity_type]
    assert_equal 'cairo_svg', entry[:glyph_source]
    assert_equal [100.0, 100.0, 150.0, 110.0], entry[:source_bbox_pdf]
  end

  def test_match_spans_normalizes_internal_items_by_media_origin
    # Internal (content-stream) items carry absolute user-space coords;
    # a shifted media box must not break matching.
    media = [10.0, 20.0, 622.0, 416.0]
    internal_item = SpanItem.new('W12X30', 'ArialNarrow', 'text_span:1:0',
                                 110.0, 120.0, 160.0, 130.0)
    pens = [{ x: 101.0, y: 101.0 }] # media-relative pen == absolute - origin
    match = CGS.match_spans(pens, [internal_item], media)
    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
  end

  def test_fixture_end_to_end_all_runs_match_their_pens
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    pens = placed.map { |entry| { x: entry[:pen_pdf][0], y: entry[:pen_pdf][1] } }
    # Declared word boxes from pdftotext -bbox-layout (y converted to y-up:
    # box_y0 = page_h - yMax, box_y1 = page_h - yMin; page_h = 396).
    spans = [
      SpanItem.new('CONDENSED', 'pdftotext', 't:1:0', 72.0, 297.93, 123.112, 307.18),
      SpanItem.new('TITLE', 'pdftotext', 't:1:1', 125.336, 297.93, 147.12, 307.18),
      SpanItem.new('BLOCK', 'pdftotext', 't:1:2', 149.344, 297.93, 176.464, 307.18),
      SpanItem.new('PARITY', 'pdftotext', 't:1:3', 178.688, 297.93, 207.584, 307.18),
      SpanItem.new('CHECK', 'pdftotext', 't:1:4', 209.808, 297.93, 237.808, 307.18),
      SpanItem.new('NORMAL', 'pdftotext', 't:1:5', 72.0, 197.516, 123.336, 208.616),
      SpanItem.new('SPAN', 'pdftotext', 't:1:6', 126.672, 197.516, 159.348, 208.616)
    ]
    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)
    assert_equal 7, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    assert_equal 0, match[:placements_unmatched],
                 'every rendered glyph pen must fall inside a declared word box'
  end

  # ── 7. report telemetry ──────────────────────────────────────────────────

  def base_stats(glyph_source)
    {
      pages: 1, primitives: 3, edges: 10, text: 7, arcs: 0,
      layers: [], elapsed_seconds: 0.2, text_renderers: [],
      text_mode: :glyphs, glyph_source: glyph_source
    }
  end

  def test_report_carries_glyph_source_block
    report = QAR.build_from_stats('x.pdf', {}, base_stats(
      source: 'cairo_svg', fallback_reason: nil, pages: 1,
      runs_matched: 7, runs_unmatched: 0, placements_unmatched: 0
    ))
    block = report[:extra][:glyph_source]
    refute_nil block
    assert_equal 'cairo_svg', block[:source]
    assert_nil block[:fallback_reason]
    assert_equal 7, block[:runs_matched]
    assert_equal 0, block[:runs_unmatched]
    signals = report[:extra][:diagnostics][:signals]
    refute_includes signals, 'glyph_source_internal_fallback'
    refute_includes signals, 'glyph_runs_unmatched'
  end

  def test_report_shows_internal_fallback_and_unmatched_runs_loudly
    report = QAR.build_from_stats('x.pdf', {}, base_stats(
      source: 'internal', fallback_reason: 'pdftocairo_missing', pages: 1,
      runs_matched: 5, runs_unmatched: 2, placements_unmatched: 0,
      missing_language_packs: ['Adobe-GB1']
    ))
    block = report[:extra][:glyph_source]
    assert_equal 'internal', block[:source]
    assert_equal 'pdftocairo_missing', block[:fallback_reason]
    assert_equal ['Adobe-GB1'], block[:missing_language_packs]
    signals = report[:extra][:diagnostics][:signals]
    assert_includes signals, 'glyph_source_internal_fallback'
    assert_includes signals, 'glyph_runs_unmatched'
    assert_includes signals, 'glyph_missing_language_packs'
  end

  def test_reports_without_glyphs_mode_are_unchanged
    stats = base_stats(nil)
    stats.delete(:glyph_source)
    stats[:text_mode] = :geometry
    report = QAR.build_from_stats('x.pdf', {}, stats)
    assert_nil report[:extra][:glyph_source]
  end

  # ── committed fixture provenance (PRIV-1 lock) ───────────────────────────
  # The SVG is the committed fixture. Its source PDF is synthetic and tiny
  # but the repo-wide *.pdf gitignore (a PRIV-1 backstop that must not gain
  # exceptions) keeps it out of version control; when it is present locally
  # (regenerated via the recipe in the header) its content is verified,
  # otherwise the check skips VISIBLY (R4-2).

  def test_fixture_svg_is_the_committed_synthetic_render
    assert File.file?(FIXTURE_SVG), 'committed SVG fixture missing'
    svg = fixture_svg
    assert svg.index('viewBox="0 0 612 396"'),
           'fixture SVG must be the synthetic condensed-span page'
    assert_operator svg.length, :<, 32_768, 'fixture SVG stays tiny'
  end

  def test_fixture_pdf_when_present_is_the_synthetic_document
    unless File.file?(FIXTURE_PDF)
      skip 'condensed_span.pdf not present (repo-wide *.pdf ignore, PRIV-1 ' \
           'backstop) — regenerate via the header recipe to run this check'
    end
    pdf = File.open(FIXTURE_PDF, 'rb') { |f| f.read }
    assert pdf.index('CONDENSED TITLE BLOCK PARITY CHECK'),
           'fixture PDF must be the synthetic condensed-span document'
    assert_operator pdf.length, :<, 2048, 'fixture PDF stays tiny'
  end
end
