#!/usr/bin/env ruby
# test/cairo_glyph_source_test.rb
#
# Round 23 (F-1) locks for the Glyphs-mode glyph SOURCE layer
# (cairo_glyph_source.rb):
#
#   1. Fixture parse -> model-space loops -> extents. The committed fixture
#      test/fixtures/cairo_glyph_source/condensed_span.svg is SYNTHETIC:
#      generated by the bundled pdftocairo (-svg -f 1 -l 1) from a
#      hand-written 696-byte PDF (base-14 Helvetica, one condensed span
#      "CONDENSED TITLE BLOCK PARITY CHECK" with Tm = [8 0 0 10 72 300],
#      i.e. 10 pt tall at 0.8 horizontal scale, plus a 12 pt "NORMAL SPAN"
#      control at (72,200) on a 612x396 page). The source PDF itself stays
#      out of version control (repo-wide *.pdf ignore = PRIV-1 backstop);
#      the content stream to regenerate it verbatim:
#        BT /F1 1 Tf 8 0 0 10 72 300 Tm (CONDENSED TITLE BLOCK PARITY CHECK) Tj ET
#        BT /F1 12 Tf 1 0 0 1 72 200 Tm (NORMAL SPAN) Tj ET
#      No owner document is involved anywhere in this test (PRIV-1).
#   2. Coordinate mapping against hand-computed values (viewBox offsets,
#      import scale, y_offset, matrix placements).
#   3. VALUE lock: the condensed span's cairo outline ink extent lands
#      within 2% (+1 pt side-bearing floor) of the PDF-DECLARED extent
#      (pdftotext -bbox-layout words, constants below).
#   4. Per-import source decision: cairo preferred; missing binary =>
#      internal source, visible fallback_reason, no silent demotion after
#      a delivered SVG page (single decision per import).
#   5. False-green guard: zero glyph ink + extractor spans = source failure.
#   6. Span matching (R17-3): runs matched/unmatched + provenance span_ids.
#   7. Report telemetry: extra.glyph_source carries source/reason/counts.
#
# Ruby 2.2 compatible syntax throughout (RB22).

require_relative 'mesh_text_scaling_test'
require_relative '../extracted/sketchup_ext/bc_pdf_vector_importer/cairo_glyph_source'
require_relative '../extracted/sketchup_ext/bc_pdf_vector_importer/qa_report'

# The shared stubs' Point3d is minimal; SvgTextRenderer's path tokenizer
# needs #distance for curve flattening and duplicate-point cleanup.
module Geom
  class Point3d
    unless method_defined?(:distance)
      def distance(other)
        dx = x.to_f - other.x.to_f
        dy = y.to_f - other.y.to_f
        dz = z.to_f - other.z.to_f
        Math.sqrt((dx * dx) + (dy * dy) + (dz * dz))
      end
    end
  end
end

class CairoGlyphSourceTest < Minitest::Test
  CGS = BlueCollarSystems::PDFVectorImporter::CairoGlyphSource
  SVG_R = BlueCollarSystems::PDFVectorImporter::SvgTextRenderer
  QAR = BlueCollarSystems::PDFVectorImporter::QAReport

  FIXTURE_DIR = File.join(File.dirname(__FILE__), 'fixtures', 'cairo_glyph_source')
  FIXTURE_SVG = File.join(FIXTURE_DIR, 'condensed_span.svg')
  FIXTURE_PDF = File.join(FIXTURE_DIR, 'condensed_span.pdf')

  # Page box of the synthetic fixture (letter-half landscape).
  FIXTURE_MEDIA_BOX = [0, 0, 612, 396].freeze

  # PDF-DECLARED extents from `pdftotext -bbox-layout condensed_span.pdf`
  # (x in PDF points; the condensed line is the five words below):
  #   CONDENSED 72.000 .. 123.112 | TITLE .. | BLOCK .. | PARITY ..
  #   CHECK 209.808 .. 237.808
  DECLARED_X0_PT = 72.0
  DECLARED_X1_PT = 237.808
  # Condensed-span baseline: Tm f = 300 (y-up); SVG pen y (top-down) = 96.
  CONDENSED_BASELINE_Y_PDF = 300.0

  def fixture_svg
    File.open(FIXTURE_SVG, 'rb') { |f| f.read }
  end

  # ── 1+2. parse -> loops -> extents, known-value coordinate mapping ──────

  def test_fixture_parses_to_placed_outline_loops
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    refute_empty placed, 'fixture must produce placed glyph outlines'
    # Every placed glyph carries loops of >= 2 points and a pen position.
    placed.each do |entry|
      refute_empty entry[:loops]
      entry[:loops].each { |pts| assert_operator pts.length, :>=, 2 }
      assert_kind_of Array, entry[:pen_pdf]
    end
    # 34 condensed chars (5 spaces -> empty defs skipped) + NORMAL SPAN.
    assert_operator placed.length, :>=, 35
  end

  def test_condensed_span_pen_positions_match_declared_baseline
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    pens = placed.map { |entry| entry[:pen_pdf] }
    condensed = pens.select { |pen| (pen[1] - CONDENSED_BASELINE_Y_PDF).abs < 0.5 }
    refute_empty condensed, 'condensed baseline pens must be found at y=300 (y-up)'
    first_pen_x = condensed.map { |pen| pen[0] }.min
    # Probe lock: first-glyph pen within 0.5 pt of the declared span xMin.
    assert_in_delta DECLARED_X0_PT, first_pen_x, 0.5
  end

  # ── 3. VALUE lock: cairo ink extent vs PDF-declared extent ──────────────

  def test_condensed_span_ink_extent_within_declared_tolerance
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    # Select the condensed line by pen baseline (y-up 300 => model inches
    # y ~ 300/72). Model space: media origin at 0, scale 1.0.
    line = placed.select do |entry|
      (entry[:pen_pdf][1] - CONDENSED_BASELINE_Y_PDF).abs < 0.5
    end
    extent = CGS.loops_extent(line)
    refute_nil extent

    ink_w_pt = (extent[2] - extent[0]) * 72.0
    declared_w_pt = DECLARED_X1_PT - DECLARED_X0_PT
    # Side-bearing-aware tolerance (probe): 2% of the declared width plus
    # a 1 pt absolute floor.
    tolerance = [declared_w_pt * 0.02, 1.0].max
    assert_in_delta declared_w_pt, ink_w_pt, tolerance,
                    'condensed cairo outline ink must land within 2% (+1pt ' \
                    'floor) of the PDF-declared span extent'
    # And the ink must sit AT the declared position, not merely match width.
    assert_in_delta DECLARED_X0_PT, extent[0] * 72.0, 1.0
    assert_in_delta DECLARED_X1_PT, extent[2] * 72.0, 1.0
  end

  def test_import_scale_and_y_offset_apply_to_loops
    placed_1x = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    placed_2x = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX,
                                      scale: 2.0, y_offset: 5.0)
    e1 = CGS.loops_extent(placed_1x)
    e2 = CGS.loops_extent(placed_2x)
    assert_in_delta e1[0] * 2.0, e2[0], 1.0e-6, 'x scales with import scale'
    assert_in_delta (e1[2] - e1[0]) * 2.0, e2[2] - e2[0], 1.0e-6
    assert_in_delta (e1[1] * 2.0) + 5.0, e2[1], 1.0e-6, 'y adds the page y_offset'
  end

  def test_known_value_coordinate_mapping_simple_use
    # Hand-checkable synthetic SVG: one square glyph (baseline-relative,
    # y negative-up), one placement at pen (72, 96) on a 612x396 page.
    # Model inches: pen x = 1.0, pen y = (396-96)/72 = 4.1666..; the glyph
    # box [0..7.2]x[-7.2..0] maps to x 1.0..1.1, y 4.1666..4.2666.
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="612pt" height="396pt" ' \
          'viewBox="0 0 612 396"><defs><g><g id="glyph-0-0">' \
          '<path d="M 0 0 L 7.2 0 L 7.2 -7.2 L 0 -7.2 Z M 0 0 "/>' \
          '</g></g></defs><g>' \
          '<use xlink:href="#glyph-0-0" x="72" y="96"/></g></svg>'
    placed = CGS.model_space_loops(svg, FIXTURE_MEDIA_BOX)
    assert_equal 1, placed.length
    assert_in_delta 72.0, placed[0][:pen_pdf][0], 1.0e-6
    assert_in_delta 300.0, placed[0][:pen_pdf][1], 1.0e-6
    extent = CGS.loops_extent(placed)
    assert_in_delta 1.0, extent[0], 1.0e-6
    assert_in_delta 1.1, extent[2], 1.0e-6
    assert_in_delta 300.0 / 72.0, extent[1], 1.0e-6
    assert_in_delta 307.2 / 72.0, extent[3], 1.0e-6
  end

  def test_known_value_coordinate_mapping_matrix_use
    # Rotated/sheared placements arrive as matrix() on the <use>; the pen is
    # the matrix translation (plus additive x/y). 90-degree rotation matrix
    # [0 1 -1 0]: local (x,-y) with y-flip maps x'=a*x-c*y, y'=-b*x+d*y.
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="612pt" height="396pt" ' \
          'viewBox="0 0 612 396"><defs><g><g id="glyph-0-0">' \
          '<path d="M 0 0 L 7.2 0 "/>' \
          '</g></g></defs><g>' \
          '<use xlink:href="#glyph-0-0" x="10" y="20" ' \
          'transform="matrix(0,1,-1,0,62,76)"/></g></svg>'
    placed = CGS.model_space_loops(svg, FIXTURE_MEDIA_BOX)
    assert_equal 1, placed.length
    assert_in_delta 72.0, placed[0][:pen_pdf][0], 1.0e-6
    assert_in_delta 300.0, placed[0][:pen_pdf][1], 1.0e-6
    pts = placed[0][:loops][0]
    # Local run along +x, rotated 90 deg: model dx = 0, dy = -b*x = -0.1 in.
    assert_in_delta 0.0, pts[1].x - pts[0].x, 1.0e-6
    assert_in_delta(-0.1, pts[1].y - pts[0].y, 1.0e-6)
  end

  # ── 4. per-import source decision + fallback on missing binary ──────────

  def with_renderer_stub(value)
    original = SVG_R.method(:find_svg_renderer)
    SVG_R.define_singleton_method(:find_svg_renderer) { value }
    yield
  ensure
    SVG_R.define_singleton_method(:find_svg_renderer, original)
  end

  def test_decision_prefers_cairo_when_pdftocairo_present
    with_renderer_stub(kind: :pdftocairo, exe: 'x') do
      stats = {}
      decision = CGS.import_decision(stats)
      assert_equal 'cairo_svg', decision[:source]
      assert_nil decision[:fallback_reason]
      assert_same decision, stats[:glyph_source], 'decision must be recorded'
      assert_same decision, CGS.import_decision(stats), 'single per-import decision'
    end
  end

  def test_decision_is_unavailable_when_no_svg_renderer
    with_renderer_stub(nil) do
      stats = {}
      decision = CGS.import_decision(stats)
      assert_equal 'unavailable', decision[:source]
      assert_equal 'pdftocairo_missing', decision[:fallback_reason]
      assert CGS.unavailable_source?(decision)
      refute CGS.svg_source?(decision)
    end
  end

  def test_decision_names_mutool_honestly
    with_renderer_stub(kind: :mutool, exe: 'x') do
      decision = CGS.import_decision({})
      assert_equal 'mupdf_svg', decision[:source]
      assert_equal 'pdftocairo_missing', decision[:fallback_reason]
      assert CGS.svg_source?(decision)
    end
  end

  def test_svg_failure_marks_source_unavailable_even_after_a_delivered_page
    with_renderer_stub(kind: :pdftocairo, exe: 'x') do
      decision = CGS.import_decision({})
      assert CGS.mark_unavailable!(decision, 'pdftocairo_timeout')
      assert_equal 'unavailable', decision[:source]
      assert_equal 'pdftocairo_timeout', decision[:fallback_reason]
      assert_equal 'cairo_svg', decision[:attempted_source]

      delivered = CGS.import_decision({})
      delivered[:pages] = 1
      assert CGS.mark_unavailable!(delivered, 'pdftocairo_failed')
      assert_equal 'unavailable', delivered[:source]
      assert_equal 1, delivered[:pages]
    end
  end

  def test_cropbox_retry_success_clears_stale_failure_and_reports_actual_media_box
    path = File.join(Dir.tmpdir, "bc_crop_retry_#{Process.pid}.svg")
    failure = {}
    runner = lambda do |args, _opts|
      File.open(path, 'wb') do |file|
        file.write('<svg width="100pt" height="100pt" viewBox="0 0 100 100"/>')
      end
      { ok: true, timed_out: false, stderr: '', stdout: '', argv: args }
    end
    validator = lambda do |_run, opts|
      if opts[:argv].first == 'crop-attempt'
        { ok: false, reason: :cropbox_rejected, diagnostics: {} }
      else
        { ok: true, reason: nil, diagnostics: {} }
      end
    end

    result = SVG_R.stub(:find_svg_renderer, { kind: :pdftocairo, exe: 'x' }) do
      SVG_R.stub(:temp_svg_path, path) do
        SVG_R.stub(:svg_render_arg_variants,
                   [['crop-attempt'], ['media-attempt']]) do
          BlueCollarSystems::PDFVectorImporter::CommandRunner.stub(:run, runner) do
            BlueCollarSystems::PDFVectorImporter::PopplerResultValidator.stub(
              :validate, validator
            ) do
              CGS.render_page_svg(
                'fixture.pdf', 1,
                failure_info: failure, use_cropbox: true
              )
            end
          end
        end
      end
    end

    refute_nil result
    assert_equal :media_box, result[:render_box_used]
    assert_equal true, result[:cropbox_fallback]
    refute failure.key?(:reason),
           'a successful retry must not retain a failed prior-attempt reason'
  ensure
    File.delete(path) if path && File.exist?(path)
  end

  def test_failure_reasons_map_to_recorded_vocabulary
    assert_equal 'pdftocairo_missing', CGS.failure_reason(reason: 'no_renderer')
    assert_equal 'pdftocairo_timeout', CGS.failure_reason(reason: 'timeout')
    assert_equal 'pdftocairo_failed', CGS.failure_reason(reason: 'render_failed')
    assert_equal 'pdftocairo_failed', CGS.failure_reason({})
    assert_equal 'svg_zero_placements', CGS.failure_reason(reason: 'svg_zero_placements')
  end

  # ── 5. false-green guard ─────────────────────────────────────────────────

  SpanItem = Struct.new(:text, :font_name, :source_span_id,
                        :bbox_x0, :bbox_y0, :bbox_x1, :bbox_y1)

  def test_zero_glyph_ink_with_extractor_spans_is_a_source_failure
    spans = [SpanItem.new('CUSTOMER', 'pdftotext', 'text_span:1:0',
                          100.0, 100.0, 150.0, 110.0)]
    assert CGS.zero_placement_false_green?({ glyphs: 0 }, spans)
    refute CGS.zero_placement_false_green?({ glyphs: 12 }, spans)
    refute CGS.zero_placement_false_green?({ glyphs: 0 }, []),
           'a genuinely empty page is not a false green'
    refute CGS.zero_placement_false_green?({ glyphs: 0 }, [SpanItem.new('  ')])
  end

  # ── 6. span matching + provenance (R17-3) ────────────────────────────────

  def test_match_spans_counts_and_provenance_span_ids
    spans = [
      SpanItem.new('AB', 'pdftotext', 'text_span:1:0',
                   100.0, 100.0, 150.0, 110.0),
      SpanItem.new('ORPHAN', 'pdftotext', 'text_span:1:1',
                   400.0, 200.0, 440.0, 210.0)
    ]
    pens = [
      { x: 101.0, y: 101.5 },  # inside CUSTOMER
      { x: 120.0, y: 102.0 },  # inside CUSTOMER
      { x: 300.0, y: 300.0 }   # matches nothing
    ]
    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)
    assert_equal 1, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    assert_equal 1, match[:placements_unmatched]
    assert_equal ['AB'], match[:matched_items].map { |i| i.text }
    assert_equal [0, 1], match[:placement_matches].map { |m| m[:placement_index] }
    assert_equal ['text_span:1:0', 'text_span:1:0'],
                 match[:placement_matches].map { |m| m[:source_span_id] }
    assert_same spans[0], match[:placement_matches][0][:item]
    assert_equal pens[2], match[:unmatched_placements][0]

    bucket = []
    CGS.record_span_provenance(bucket, 1, match[:matched_items], 'cairo_svg')
    assert_equal 1, bucket.length
    entry = bucket[0]
    assert_equal 'text_span:1:0', entry[:span_id]
    assert_equal 'glyph_outline', entry[:created_entity_type]
    assert_equal 'cairo_svg', entry[:glyph_source]
    assert_equal [100.0, 100.0, 150.0, 110.0], entry[:source_bbox_pdf]
  end

  def test_match_spans_normalizes_internal_items_by_media_origin
    # Internal (content-stream) items carry absolute user-space coords;
    # a shifted media box must not break matching.
    media = [10.0, 20.0, 622.0, 416.0]
    internal_item = SpanItem.new('A', 'ArialNarrow', 'text_span:1:0',
                                 110.0, 120.0, 160.0, 130.0)
    pens = [{ x: 101.0, y: 101.0 }] # media-relative pen == absolute - origin
    match = CGS.match_spans(pens, [internal_item], media)
    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
  end

  def test_match_spans_never_reuses_one_glyph_pen_to_certify_two_source_items
    spans = [
      SpanItem.new('A', 'pdftotext', 'text_span:1:0',
                   100.0, 100.0, 150.0, 110.0),
      SpanItem.new('B', 'pdftotext', 'text_span:1:1',
                   100.0, 100.0, 150.0, 110.0)
    ]

    match = CGS.match_spans([{ x: 110.0, y: 105.0 }], spans,
                            FIXTURE_MEDIA_BOX)

    assert_equal 1, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    assert_equal 0, match[:placements_unmatched]
    assert_equal ['A'], match[:matched_items].map { |item| item.text }
    assert_equal 1, match[:placement_matches].length
    assert_equal 'text_span:1:0', match[:placement_matches][0][:source_span_id]
    assert_same spans[0], match[:placement_matches][0][:item]
  end

  def test_match_spans_reassigns_overlap_pen_to_complete_both_source_items
    # A nearest-center greedy assignment gives all three pens to the broad
    # first box and falsely reports both spans as incomplete. The allocator
    # must reserve the only shared pen for the narrow span while using the two
    # broad-only pens for the first span.
    spans = [
      SpanItem.new('AA', 'pdftotext', 'text_span:1:0',
                   0.0, 0.0, 20.0, 10.0),
      SpanItem.new('B', 'pdftotext', 'text_span:1:1',
                   8.0, 0.0, 12.0, 10.0)
    ]
    pens = [
      { x: 1.0, y: 5.0, placement_index: 10 },
      { x: 10.0, y: 5.0, placement_index: 11 },
      { x: 19.0, y: 5.0, placement_index: 12 }
    ]

    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)

    assert_equal 2, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    assert_equal 0, match[:placements_unmatched]
    by_span = match[:placement_matches].group_by do |entry|
      entry[:source_span_id]
    end
    broad_indices = by_span['text_span:1:0'].map do |entry|
      entry[:placement_index]
    end.sort
    narrow_indices = by_span['text_span:1:1'].map do |entry|
      entry[:placement_index]
    end
    assert_equal [10, 12], broad_indices
    assert_equal [11], narrow_indices
  end

  def test_one_glyph_pen_cannot_certify_a_long_source_span
    span = SpanItem.new(
      'ABCDEFGHIJ', 'pdftotext', 'text_span:1:0',
      100.0, 100.0, 200.0, 120.0
    )

    match = CGS.match_spans(
      [{ x: 110.0, y: 110.0, placement_index: 7 }],
      [span], FIXTURE_MEDIA_BOX
    )

    assert_equal 0, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    assert_equal 1, match[:placements_unmatched]
    assert_empty match[:placement_matches]
    failure = match[:coverage_failures].first
    assert_equal 'text_span:1:0', failure[:source_span_id]
    assert_equal 10, failure[:expected_glyph_count]
    assert_equal 1, failure[:observed_glyph_count]
    assert_equal :glyph_coverage_mismatch, failure[:reason]
  end

  def test_surplus_pen_inside_one_span_prevents_false_exact_association
    span = SpanItem.new(
      'A', 'pdftotext', 'text_span:1:0',
      100.0, 100.0, 200.0, 120.0
    )
    pens = [
      { x: 110.0, y: 110.0, placement_index: 7 },
      { x: 120.0, y: 110.0, placement_index: 8 }
    ]

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 0, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    assert_equal 2, match[:placements_unmatched]
    assert_empty match[:placement_matches]
    failure = match[:coverage_failures].first
    assert_equal 1, failure[:expected_glyph_count]
    assert_equal 2, failure[:observed_glyph_count]
  end

  def test_each_visible_source_character_requires_one_owned_glyph_placement
    span = SpanItem.new(
      'A B', 'pdftotext', 'text_span:1:0',
      100.0, 100.0, 200.0, 120.0
    )
    pens = [
      { x: 110.0, y: 110.0, placement_index: 3 },
      { x: 150.0, y: 110.0, placement_index: 4 }
    ]

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    assert_equal 0, match[:placements_unmatched]
    placement_indices = match[:placement_matches].map do |entry|
      entry[:placement_index]
    end
    assert_equal [3, 4], placement_indices
    assert_empty match[:coverage_failures]
  end

  def test_shaped_source_ink_can_certify_a_ligature_without_character_count_parity
    span = SpanItem.new(
      'office', 'pdftotext', 'text_span:1:0',
      0.0, 0.0, 60.0, 10.0
    )
    pens = 5.times.map do |index|
      {
        x: (index * 12.0) + 1.0, y: 5.0, placement_index: index,
        ink_bbox_pdf: [index * 12.0, 1.0, (index + 1) * 12.0, 9.0]
      }
    end

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    assert_equal [0, 1, 2, 3, 4],
                 match[:placement_matches].map { |entry| entry[:placement_index] }
    assert_empty match[:coverage_failures]
    evidence = match[:source_ink_matches].first
    assert_equal 4, evidence[:minimum_shaped_glyph_count]
    assert evidence[:shaped_glyph_count_verified]
  end

  def test_contextual_non_ascii_shaping_is_not_blocked_by_unicode_count
    span = SpanItem.new(
      "\u0644\u0627", 'pdftotext', 'text_span:1:arabic',
      0.0, 0.0, 40.0, 12.0
    )
    pens = [{
      :x => 20.0, :y => 6.0, :placement_index => 0,
      :ink_bbox_pdf => [0.0, 1.0, 40.0, 11.0]
    }]

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    evidence = match[:source_ink_matches].first
    assert_equal 2, evidence[:minimum_shaped_glyph_count]
    assert_equal false, evidence[:character_count_parity]
    assert_equal false, evidence[:shaped_glyph_count_verified]
    assert evidence[:source_ink_coverage_verified]
  end

  def test_finite_ascii_shaping_bound_does_not_excuse_unrelated_missing_glyphs
    assert_equal 10, CGS.minimum_shaped_glyph_count(
      SpanItem.new('TENLETTERS')
    )
    assert_equal 11, CGS.minimum_shaped_glyph_count(
      SpanItem.new('Significance')
    )
    assert_equal 4, CGS.minimum_shaped_glyph_count(
      SpanItem.new('office')
    )
  end

  def test_source_ink_coverage_does_not_certify_a_partial_long_span
    span = SpanItem.new(
      'ABCDEFGHIJ', 'pdftotext', 'text_span:1:0',
      0.0, 0.0, 100.0, 10.0
    )
    pens = [{
      x: 1.0, y: 5.0, placement_index: 7,
      ink_bbox_pdf: [0.0, 1.0, 10.0, 9.0]
    }]

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 0, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    failure = match[:coverage_failures].first
    assert_equal :source_ink_coverage_incomplete, failure[:reason]
    assert_equal false, failure[:source_ink_coverage_verified]
  end

  def test_source_ink_overlap_owns_shared_baseline_pens_by_physical_row
    spans = [
      SpanItem.new('AB', 'pdftotext', 'text_span:1:0', 0.0, 10.0, 20.0, 20.0),
      SpanItem.new('CD', 'pdftotext', 'text_span:1:1', 0.0, 0.0, 20.0, 10.0)
    ]
    pens = [
      { x: 1.0, y: 10.0, placement_index: 0,
        ink_bbox_pdf: [0.0, 12.0, 10.0, 18.0] },
      { x: 11.0, y: 10.0, placement_index: 1,
        ink_bbox_pdf: [10.0, 12.0, 20.0, 18.0] },
      { x: 1.0, y: 10.0, placement_index: 2,
        ink_bbox_pdf: [0.0, 2.0, 10.0, 8.0] },
      { x: 11.0, y: 10.0, placement_index: 3,
        ink_bbox_pdf: [10.0, 2.0, 20.0, 8.0] }
    ]

    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)
    by_span = match[:placement_matches].group_by do |entry|
      entry[:source_span_id]
    end

    assert_equal 2, match[:runs_matched]
    top_indices = by_span['text_span:1:0'].map do |entry|
      entry[:placement_index]
    end
    bottom_indices = by_span['text_span:1:1'].map do |entry|
      entry[:placement_index]
    end
    assert_equal [0, 1], top_indices
    assert_equal [2, 3], bottom_indices
  end

  def test_source_ink_ownership_does_not_require_pen_inside_span
    span = SpanItem.new(
      'A', 'pdftotext', 'text_span:1:0',
      10.0, 0.0, 20.0, 10.0
    )
    pens = [{
      x: 0.0, y: 5.0, placement_index: 3,
      ink_bbox_pdf: [10.0, 1.0, 20.0, 9.0]
    }]

    match = CGS.match_spans(pens, [span], FIXTURE_MEDIA_BOX)

    assert_equal 1, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    indices = match[:placement_matches].map do |entry|
      entry[:placement_index]
    end
    assert_equal [3], indices
  end

  def test_rotated_span_requires_ink_coverage_along_semantic_text_angle
    rotated_span_class = Struct.new(
      :text, :font_name, :source_span_id,
      :bbox_x0, :bbox_y0, :bbox_x1, :bbox_y1, :angle
    )
    source = rotated_span_class.new(
      'AB', 'pdftotext', 'text_span:1:vertical',
      0.0, 0.0, 10.0, 100.0, -90.0
    )
    pens = [
      {
        :x => 5.0, :y => 45.0, :placement_index => 0,
        :ink_bbox_pdf => [0.0, 40.0, 10.0, 50.0],
        :source_primary_axis => :x
      },
      {
        :x => 5.0, :y => 55.0, :placement_index => 1,
        :ink_bbox_pdf => [0.0, 50.0, 10.0, 60.0],
        :source_primary_axis => :x
      }
    ]

    match = CGS.match_spans(pens, [source], [0.0, 0.0, 200.0, 200.0])

    assert_equal 0, match[:runs_matched]
    assert_equal 1, match[:runs_unmatched]
    refute match[:coverage_failures][0][:source_ink_coverage_verified]
  end

  def test_model_space_loops_deduplicates_only_exact_physical_svg_uses
    svg = <<-SVG
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
  <defs><g id="glyph-0-0"><path d="M 0 0 L 10 0 L 10 -10 L 0 -10 Z"/></g></defs>
  <use xlink:href="#glyph-0-0" x="10" y="20"/>
  <use xlink:href="#glyph-0-0" x="10" y="20"/>
  <use xlink:href="#glyph-0-0" x="10.0000000004" y="20"/>
</svg>
    SVG

    placed = CGS.model_space_loops(svg, [0, 0, 100, 100])

    assert_equal 2, placed.length,
                 'exact duplicate ink is one physical outline; nearby ink is distinct'
    assert_equal [0, 2], placed.map { |entry| entry[:placement_index] }
    placed.each do |entry|
      assert_equal 4, entry[:ink_bbox_pdf].length
    end
  end

  def test_loop_binding_rejects_same_bbox_contour_mutation
    svg = <<-SVG
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
  <defs><g id="glyph-0-0"><path d="M 0 0 L 10 0 L 10 -10 L 5 -8 L 0 -10 Z"/></g></defs>
  <use xlink:href="#glyph-0-0" x="10" y="20"/>
</svg>
    SVG
    placed = CGS.model_space_loops(svg, [0, 0, 100, 100])
    original = placed[0][:loops][0][3]
    placed[0][:loops][0][3] = Geom::Point3d.new(
      original.x.to_f + 0.01, original.y.to_f + 0.01, 0.0
    )

    binding = CGS.verify_model_loop_bindings(
      svg, [0, 0, 100, 100], placed
    )

    refute binding[:ok],
           'a matching bbox cannot certify a physically different contour'
    assert binding[:failures].any? { |failure| failure[:field] == :source_contours }
  end

  def test_curved_contour_inventory_is_scale_invariant_and_source_bound
    svg = <<-SVG
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
  <defs><g id="glyph-0-0"><path d="M 0 0 C 0.5 0 1 -1 2 -2 L 0 -2 Z"/></g></defs>
  <use xlink:href="#glyph-0-0" x="10" y="20"/>
</svg>
    SVG

    full = CGS.model_space_loops(svg, [0, 0, 100, 100], :scale => 1.0)
    tiny = CGS.model_space_loops(svg, [0, 0, 100, 100], :scale => 0.1)

    assert_equal full[0][:loops][0].length, tiny[0][:loops][0].length,
                 'import scale must not change a source glyph contour inventory'
    assert CGS.verify_model_loop_bindings(
      svg, [0, 0, 100, 100], full, :scale => 1.0
    )[:ok]
    assert CGS.verify_model_loop_bindings(
      svg, [0, 0, 100, 100], tiny, :scale => 0.1
    )[:ok]
  end

  def test_model_space_loops_keep_deterministic_svg_placement_indices
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    indices = placed.map { |entry| entry[:placement_index] }
    assert_equal indices.sort, indices
    assert_equal indices.uniq, indices
    assert_equal 0, indices.first
    assert_operator indices.last, :>=, placed.length - 1,
                    'empty glyph definitions may leave intentional index gaps'
  end

  def test_fixture_end_to_end_all_runs_match_their_pens
    placed = CGS.model_space_loops(fixture_svg, FIXTURE_MEDIA_BOX)
    pens = placed.map { |entry| { x: entry[:pen_pdf][0], y: entry[:pen_pdf][1] } }
    # Declared word boxes from pdftotext -bbox-layout (y converted to y-up:
    # box_y0 = page_h - yMax, box_y1 = page_h - yMin; page_h = 396).
    spans = [
      SpanItem.new('CONDENSED', 'pdftotext', 't:1:0', 72.0, 297.93, 123.112, 307.18),
      SpanItem.new('TITLE', 'pdftotext', 't:1:1', 125.336, 297.93, 147.12, 307.18),
      SpanItem.new('BLOCK', 'pdftotext', 't:1:2', 149.344, 297.93, 176.464, 307.18),
      SpanItem.new('PARITY', 'pdftotext', 't:1:3', 178.688, 297.93, 207.584, 307.18),
      SpanItem.new('CHECK', 'pdftotext', 't:1:4', 209.808, 297.93, 237.808, 307.18),
      SpanItem.new('NORMAL', 'pdftotext', 't:1:5', 72.0, 197.516, 123.336, 208.616),
      SpanItem.new('SPAN', 'pdftotext', 't:1:6', 126.672, 197.516, 159.348, 208.616)
    ]
    match = CGS.match_spans(pens, spans, FIXTURE_MEDIA_BOX)
    assert_equal 7, match[:runs_matched]
    assert_equal 0, match[:runs_unmatched]
    assert_equal 0, match[:placements_unmatched],
                 'every rendered glyph pen must fall inside a declared word box'
  end

  # ── 7. report telemetry ──────────────────────────────────────────────────

  def base_stats(glyph_source)
    {
      pages: 1, primitives: 3, edges: 10, text: 7, arcs: 0,
      layers: [], elapsed_seconds: 0.2, text_renderers: [],
      text_mode: :glyphs, glyph_source: glyph_source
    }
  end

  def test_report_carries_glyph_source_block
    report = QAR.build_from_stats('x.pdf', {}, base_stats(
      source: 'cairo_svg', fallback_reason: nil, pages: 1,
      runs_matched: 7, runs_unmatched: 0, placements_unmatched: 0
    ))
    block = report[:extra][:glyph_source]
    refute_nil block
    assert_equal 'cairo_svg', block[:source]
    assert_nil block[:fallback_reason]
    assert_equal 7, block[:runs_matched]
    assert_equal 0, block[:runs_unmatched]
    signals = report[:extra][:diagnostics][:signals]
    refute_includes signals, 'glyph_source_internal_fallback'
    refute_includes signals, 'glyph_source_unavailable'
    refute_includes signals, 'glyph_runs_unmatched'
  end

  def test_report_shows_unavailable_source_and_unmatched_runs_loudly
    report = QAR.build_from_stats('x.pdf', {}, base_stats(
      source: 'unavailable', attempted_source: 'cairo_svg',
      fallback_reason: 'pdftocairo_missing', pages: 1,
      runs_matched: 5, runs_unmatched: 2, placements_unmatched: 0,
      missing_language_packs: ['Adobe-GB1']
    ))
    block = report[:extra][:glyph_source]
    assert_equal 'unavailable', block[:source]
    assert_equal 'pdftocairo_missing', block[:fallback_reason]
    assert_equal ['Adobe-GB1'], block[:missing_language_packs]
    signals = report[:extra][:diagnostics][:signals]
    assert_includes signals, 'glyph_source_unavailable'
    refute_includes signals, 'glyph_source_internal_fallback'
    assert_includes signals, 'glyph_runs_unmatched'
    assert_includes signals, 'glyph_missing_language_packs'
  end

  def test_reports_without_glyphs_mode_are_unchanged
    stats = base_stats(nil)
    stats.delete(:glyph_source)
    stats[:text_mode] = :geometry
    report = QAR.build_from_stats('x.pdf', {}, stats)
    assert_nil report[:extra][:glyph_source]
  end

  # ── committed fixture provenance (PRIV-1 lock) ───────────────────────────
  # The SVG is the committed fixture. Its source PDF is synthetic and tiny
  # but the repo-wide *.pdf gitignore (a PRIV-1 backstop that must not gain
  # exceptions) keeps it out of version control; when it is present locally
  # (regenerated via the recipe in the header) its content is verified,
  # otherwise the check skips VISIBLY (R4-2).

  def test_fixture_svg_is_the_committed_synthetic_render
    assert File.file?(FIXTURE_SVG), 'committed SVG fixture missing'
    svg = fixture_svg
    assert svg.index('viewBox="0 0 612 396"'),
           'fixture SVG must be the synthetic condensed-span page'
    assert_operator svg.length, :<, 32_768, 'fixture SVG stays tiny'
  end

  def test_fixture_pdf_when_present_is_the_synthetic_document
    unless File.file?(FIXTURE_PDF)
      skip 'condensed_span.pdf not present (repo-wide *.pdf ignore, PRIV-1 ' \
           'backstop) — regenerate via the header recipe to run this check'
    end
    pdf = File.open(FIXTURE_PDF, 'rb') { |f| f.read }
    assert pdf.index('CONDENSED TITLE BLOCK PARITY CHECK'),
           'fixture PDF must be the synthetic condensed-span document'
    assert_operator pdf.length, :<, 2048, 'fixture PDF stays tiny'
  end
end
